import Head from "next/head";
import {
  AiFillFacebook,
  AiFillLinkedin,
  AiFillInstagram,
} from "react-icons/ai";
import Image from "next/image";
import ts from "../public/ts.png";
import lanugage from "../public/language.png";
import cert from "../public/cert.png";
import { motion as m } from "framer-motion";
import Link from "next/link";
import React, { useState } from 'react';
import ImageCarousel from './ImageCarousel';

const Home = () => {
  return (
    <div>
      <Head>
        <title>Choo Zheng Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/PFicon.png" />
      </Head>

      <main className="bg-white px-10 pb-10 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-0 flex justify-between">
            <m.div
              initial={{ opacity: 0, x: "-20%" }}
              animate={{ opacity: 1, x: "0%" }}
              transition={{ duration: 1, ease: "easeOut" }}
            >
              <h1
                className="text-3xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-cyan-500 to-teal-500 cursor-pointer transition duration-300 hover:scale-105"
                onClick={() => window.location.reload()}
              >
                ZHENG / PORTFOLIO
              </h1>
            </m.div>
            <ul className="flex items-center">
              <li>
                <m.div
                  initial={{ opacity: 0, x: "20%" }}
                  animate={{ opacity: 1, x: "0%" }}
                  transition={{ duration: 1, ease: "easeOut" }}
                >
                  <a
                    className="text-xl bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 font-medium
                    hover:from-cyan-600 hover:to-teal-600 hover:scale-105 hover:shadow-md hover:rotate-1 transition duration-300"
                    href="https://drive.google.com/file/d/132wGRfAY_4IQzmyyKvWJy0_4VF0YQYCg/view?usp=sharing"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <span className="hidden md:inline-block">VIEW</span> RESUME
                  </a>
                </m.div>
              </li>
            </ul>
          </nav>
          <hr className="h-px my-2 bg-gray-200 border-0 dark:bg-gray-700"></hr>
          <m.div
            initial={{ opacity: 0, y: "20%" }}
            animate={{ opacity: 1, y: "0%" }}
            transition={{ duration: 1, ease: "easeOut" }}
            className="text-center p-10"
          >
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Choo Zheng
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl">
              Computer Science (Final Year Student)
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-3xl mx-auto">
              As an aspiring Computer Science student specializing in
              <span className="text-teal-500">
                {" "}
                <br></br>Cyber Security{" "}
              </span>
              from
              <span className="text-teal-500"> Taylor&apos;s University</span>,
              <br></br>I am passionate about software development and creating
              innovative solutions.
            </p>
          </m.div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <m.div
              initial={{ opacity: 0, y: "150%" }}
              animate={{ opacity: 1, y: "0%" }}
              transition={{ duration: 0.5, ease: "easeOut" }}
            >
              <a
                href="https://www.facebook.com/choozheng0422"
                target="_blank"
                rel="noopener noreferrer"
                className="flex justify-center items-center"
              >
                <AiFillFacebook />
                <span className="text-sm font-medium hidden md:inline-block">@ Choo Zheng</span>
              </a>
            </m.div>

            <m.div
              initial={{ opacity: 0, y: "150%" }}
              animate={{ opacity: 1, y: "0%" }}
              transition={{ duration: 0.8, ease: "easeOut" }}
              className="flex justify-center items-center"
            >
              <a
                href="https://www.instagram.com/choozheng0422/"
                target="_blank"
                rel="noopener noreferrer"
                className="flex justify-center items-center"
              >
                <AiFillInstagram />
                <span className="text-sm font-medium hidden md:inline-block">@ choozheng0422</span>
              </a>
            </m.div>

            <m.div
              initial={{ opacity: 0, y: "150%" }}
              animate={{ opacity: 1, y: "0%" }}
              transition={{ duration: 1.1, ease: "easeOut" }}
            >
              <a
                href="https://www.linkedin.com/in/choo-zheng-6571a5278/"
                target="_blank"
                rel="noopener noreferrer"
                className="flex justify-center items-center"
              >
                <AiFillLinkedin />
                <span className="text-sm font-medium hidden md:inline-block">@ Choo Zheng</span>
              </a>
            </m.div>
          </div>
          <div className="-mt-40 flex justify-center items-center h-screen">
            <ImageCarousel />
          </div>
        </section>

        <section>
          <m.div
            initial={{ opacity: 0, y: "100%" }}
            animate={{ opacity: 1, y: "0%" }}
            transition={{ duration: 1, ease: "easeOut" }}
            className="-mt-40"
          >
            <h3 className="text-center text-3xl py-10 md:text-4xl">About Me</h3>
            <p className="text-justify leading-8 text-gray-800 max-w-lg mx-auto">
              My academic journey includes a
              <span className="text-teal-500">
                {" "}
                Business Specialization Course
              </span>{" "}
              at
              <span className="text-teal-500">
                {" "}
                Anglo-American University
              </span>{" "}
              in
              <span className="text-teal-500"> Prague, Czech Republic </span>
              during August 2022 as part of a student exchange semester. Through
              various university projects, I have gained proficiency in multiple
              programming languages, solidifying my technical skills.
            </p>
          </m.div>

          <div className="py-10 lg:flex gap-10 justify-center ">
            {/*Technical Skills*/}
            <div>
              <div className="shadow-lg p-20 rounded-xl my-10">
                <div className="flex justify-center items-center">
                  <Image
                    src={ts}
                    alt="technical skills"
                    width={180}
                    height={180}
                  />
                </div>
                <h3 className="text-lg text-center font-medium pt-8 pb-2 text-teal-600">
                  Technical Skills
                </h3>
                <p className="text-gray-800 py-4 px-2">
                  <img src="/py.png" alt="uk" className="inline-block h-5 mr-2" />
                  Python
                </p>
                <div className="w-full bg-gray-200 rounded-full h-2 dark:bg-gray-700">
                  <div
                    className="bg-gradient-to-r from-cyan-500 to-teal-500 h-2 rounded-full "
                    style={{ width: "60%" }}
                  ></div>
                </div>
                <p className="text-gray-800 py-4 px-2"> 
                <img src="/java.png" alt="uk" className="inline-block h-5 mr-2" />
                Java
                </p>
                <div className="w-full bg-gray-200 rounded-full h-2 dark:bg-gray-700">
                  <div
                    className="bg-gradient-to-r from-cyan-500 to-teal-500 h-2 rounded-full "
                    style={{ width: "70%" }}
                  ></div>
                </div>
                <p className="text-gray-800 py-4 px-2"> 
                <img src="/c++.png" alt="uk" className="inline-block h-5 mr-2" />
                C++
                </p>
                <div className="w-full bg-gray-200 rounded-full h-2 dark:bg-gray-700">
                  <div
                    className="bg-gradient-to-r from-cyan-500 to-teal-500 h-2 rounded-full "
                    style={{ width: "40%" }}
                  ></div>
                </div>
                <p className="text-gray-800 py-4 px-2"> 
                <img src="/mysql.png" alt="uk" className="inline-block h-5 mr-2" />
                MySQL
                </p>
                <div className="w-full bg-gray-200 rounded-full h-2 dark:bg-gray-700">
                  <div
                    className="bg-gradient-to-r from-cyan-500 to-teal-500 h-2 rounded-full "
                    style={{ width: "70%" }}
                  ></div>
                </div>
                <p className="text-gray-800 py-4 px-2">
                <img src="/html.png" alt="uk" className="inline-block h-5 mr-2" />
                  HTML, CSS, JavaScript & PHP
                </p>
                <div className="w-full bg-gray-200 rounded-full h-2 dark:bg-gray-700">
                  <div
                    className="bg-gradient-to-r from-cyan-500 to-teal-500 h-2 rounded-full "
                    style={{ width: "80%" }}
                  ></div>
                </div>
                <p className="text-gray-800 py-4 px-2"> 
                <img src="/figma.png" alt="uk" className="inline-block h-5 mr-2" />
                Figma
                </p>
                <div className="w-full bg-gray-200 rounded-full h-2 dark:bg-gray-700">
                  <div
                    className="bg-gradient-to-r from-cyan-500 to-teal-500 h-2 rounded-full "
                    style={{ width: "85%" }}
                  ></div>
                </div>
              </div>
            </div>

            {/*Certifications*/}
            <div>
              <div className="shadow-lg p-10 rounded-xl my-10 ">
                <div className="flex justify-center items-center">
                  <Image src={cert} alt="cert" width={180} height={180} />
                </div>
                <h3 className="text-center text-lg font-medium pt-8 pb-2 text-teal-600">
                  Certifications
                </h3>
                <ul className="list-disc ml-5">
                  <li className="text-gray-800 py-3 px-2">
                    {" "}
                    Oracle Java Foundations
                  </li>
                  <li className="text-gray-800 py-3 px-2">
                    {" "}
                    Huawei Data Communications & <br />
                    Network Technology
                  </li>
                  <li className="text-gray-800 py-3 px-2">
                    {" "}
                    Salesforce Fundamentals
                  </li>
                  <li className="text-gray-800 py-3 px-2">
                    {" "}
                    Google Digital Garage <br />
                    (The Fundamentals of Digital Marketing)
                  </li>
                </ul>
              </div>
            </div>

            {/*Language Proficiency*/}
            <div>
              <div className="shadow-lg p-20 rounded-xl my-10 ">
                <div className="flex justify-center items-center">
                  <Image
                    src={lanugage}
                    alt="language"
                    width={150}
                    height={150}
                  />
                </div>
                <h3 className="text-center text-lg font-medium pt-8 pb-2 text-teal-600">
                  Language Proficiency
                </h3>
                <p className="text-gray-800 py-4 px-2">
                  <img src="/uk.png" alt="uk" className="inline-block h-5 mr-2" />
                  English
                </p>
                <div className="w-full bg-gray-200 rounded-full h-2 dark:bg-gray-700">
                  <div
                    className="bg-gradient-to-r from-cyan-500 to-teal-500 h-2 rounded-full "
                    style={{ width: "70%" }}
                  ></div>
                </div>
                <p className="text-gray-800 py-4 px-2">
                  <img src="/cn.png" alt="uk" className="inline-block h-5 mr-2" />
                  Mandarin
                </p>
                <div className="w-full bg-gray-200 rounded-full h-2 dark:bg-gray-700">
                  <div
                    className="bg-gradient-to-r from-cyan-500 to-teal-500 h-2 rounded-full "
                    style={{ width: "90%" }}
                  ></div>
                </div>
                <p className="text-gray-800 py-4 px-2">
                  <img src="/my.png" alt="uk" className="inline-block h-5 mr-2" />
                  Malay
                </p>
                <div className="w-full bg-gray-200 rounded-full h-2 dark:bg-gray-700">
                  <div
                    className="bg-gradient-to-r from-cyan-500 to-teal-500 h-2 rounded-full "
                    style={{ width: "60%" }}
                  ></div>
                </div>
                <p className="text-gray-800 py-4 px-2">
                  <img src="/hk.png" alt="uk" className="inline-block h-5 mr-2" />
                  Cantonese
                </p>
                <div className="w-full bg-gray-200 rounded-full h-2 dark:bg-gray-700">
                  <div
                    className="bg-gradient-to-r from-cyan-500 to-teal-500 h-2 rounded-full "
                    style={{ width: "90%" }}
                  ></div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section>
          <m.div
            className="flex justify-center items-center"
            initial={{ opacity: 0, x: "20%" }}
            animate={{ opacity: 1, x: "0%" }}
            transition={{ duration: 1, ease: "easeOut" }}
          >
            <Link href="/mywork">
              <div
                className="text-xl flex justify-center items-center text-center bg-gradient-to-r from-cyan-500 to-teal-500 
             hover:from-cyan-600 hover:to-teal-600 
             text-white px-4 py-2 rounded-md ml-8 font-medium 
             hover:scale-105 hover:shadow-md hover:rotate-1
             transition duration-300"
                style={{ width: "180px", height: "50px" }}
              >
                View Project
              </div>
            </Link>
          </m.div>
        </section>
      </main>
    </div>
  );
};

export default Home;
